# -*- coding: utf-8 -*-
"""Untitled23.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IXiU5ewfThcpLjdYWF_EnHp_tqiJZZ4s
"""

n=int(input())
count=0
for i in range(1,n):
  if(n%i==0):
    count=count+i
if(count==n):
  print("perfect number")
else:
  print("not perfect number")