# -*- coding: utf-8 -*-
"""Untitled23.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IXiU5ewfThcpLjdYWF_EnHp_tqiJZZ4s
"""

n=int(input())
count=0
count1=0
for i in range(1,n+1):
  if i%2==0:
    count=count+1
  else:
    count1=count1+1 
print("even numbers=",count,"odd numbers=",count1)

