# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pFnsKCbsCKpaist-RGZA3MIn3AgUspC5
"""

#add natural numbers sum=1+2+3+......+n
sum=0
n=int(input("enter the n value"))
for i in range(1,n+1):
  sum=sum+i
print(sum)