# -*- coding: utf-8 -*-
"""Untitled23.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IXiU5ewfThcpLjdYWF_EnHp_tqiJZZ4s
"""

n=int(input())
count=0
num=0
while(n>0): 
  n=n//10
  count=count+1
print(count)