# -*- coding: utf-8 -*-
"""Untitled23.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IXiU5ewfThcpLjdYWF_EnHp_tqiJZZ4s
"""

n=int(input())
sum=0
for i in range(1,n+1):
  sum=sum+i
  avg=sum/2
print("sum of numbers=",sum,"","average of numbers=",avg)