# -*- coding: utf-8 -*-
"""Untitled23.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IXiU5ewfThcpLjdYWF_EnHp_tqiJZZ4s
"""

rev=0
n=int(input())
while(n>0):
  r=n%10
  rev=rev*10+r

  n=n//10
print("Reverse of a number",rev)

