# -*- coding: utf-8 -*-
"""Untitled23.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IXiU5ewfThcpLjdYWF_EnHp_tqiJZZ4s
"""

x=[1,0]
y=[0,1]
for i in x:
  for j in y:
    if(i==j):
      continue
    else:
      print(i,j)