# -*- coding: utf-8 -*-
"""Untitled23.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IXiU5ewfThcpLjdYWF_EnHp_tqiJZZ4s
"""

pn=0
n=int(input())
while(n>0):
  r=n%10
  pn=pn*10+r
  n=n//10
print("palindrome of a number",pn)

